### PR TITLE
Add Alertmanager ServiceMonitor

### PR DESCRIPTION
**Pull request by mcbenjemaa**
Towards https://github.com/giantswarm/giantswarm/issues/25300

Add Alertmanager ServiceMonitor resource

### CODE REVIEW

**Comment by mcbenjemaa** [comment]
Tested ✅

**Review by QuantumEnigmaa — APPROVED** [review]

**Review by QuentinBisson — CHANGES_REQUESTED** [review]
Why do we need it in go instead of a helm template ?

**Comment by QuentinBisson** [comment]
This is the generated template by pmo:

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    policies.kyverno.io/last-applied-patches: |
      configure-service-monitor-labelling-schema.configure-service-monitor-labelling-schema.kyverno.io: added
        /spec/endpoints/0/relabelings
  creationTimestamp: "2023-01-19T13:52:17Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: alertmanager
    app.kubernetes.io/managed-by: prometheus-meta-operator
    app.kubernetes.io/name: alertmanager
  name: alertmanager
  namespace: monitoring
  resourceVersion: "911728624"
  uid: 6c1cc998-4f6b-4ec8-a1bd-2f60977c5f92
spec:
  endpoints:
  - bearerTokenSecret:
      key: ""
    enableHttp2: true
    path: /metrics
    port: web
    relabelings:
    - action: replace
      replacement: gaia
      targetLabel: cluster_id
    - action: replace
      replacement: management_cluster
      targetLabel: cluster_type
    - action: replace
      replacement: highest
      targetLabel: service_priority
    - action: replace
      replacement: aws
      targetLabel: provider
    - action: replace
      replacement: gaia
      targetLabel: installation
    - action: replace
      regex: ;(.*)
      replacement: $1
      separator: ;
      sourceLabels:
      - namespace
      - __meta_kubernetes_namespace
      targetLabel: namespace
    - action: replace
      sourceLabels:
      - __meta_kubernetes_pod_label_app_kubernetes_io_name
      targetLabel: app
    - action: replace
      sourceLabels:
      - __meta_kubernetes_pod_label_app_kubernetes_io_instance
      targetLabel: instance
    - action: replace
      sourceLabels:
      - __meta_kubernetes_pod_name
      targetLabel: pod
    - action: replace
      sourceLabels:
      - __meta_kubernetes_pod_container_name
      targetLabel: container
    - action: replace
      sourceLabels:
      - __meta_kubernetes_pod_node_name
      targetLabel: node
    - action: replace
      sourceLabels:
      - __meta_kubernetes_node_label_role
      targetLabel: role
    - action: replace
      replacement: giantswarm
      targetLabel: customer
    - action: replace
      replacement: monitoring
      targetLabel: organization
    - action: replace
      regex: org-(.*)
      replacement: ${1}
      sourceLabels:
      - organization
      targetLabel: organization
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      operated-alertmanager: "true"


Let's keep only what we need

**Comment by mcbenjemaa** [comment]
@QuentinBisson Since Alertmanager is managed by PMO, I preferred to manage the ServiceMonitor the same way..

**Comment by mcbenjemaa** [comment]
@QuentinBisson Do you agree?
 otherwise where you want to keep this resource managed?

**Comment by QuentinBisson** [comment]
TBH i don't see how it makes sense to create 5 go files instead of a one yaml file in the helm template (even more because you did not add any test )

**Comment by QuentinBisson** [comment]
Also unrelated but I think we Can replace thé alertmanager resource with a yaml file instead

**Comment by mcbenjemaa** [comment]
So, in which repo you want to add this?

**Comment by mcbenjemaa** [comment]
let's discuss this on Monday.

**Review by QuentinBisson — APPROVED** [review]

**Pull request merged**
