### PR TITLE
Cleanup rw old secrets

### PR DESCRIPTION
**Pull request by mcbenjemaa**
Towards https://github.com/giantswarm/giantswarm/issues/24222

### CODE REVIEW

**Review by TheoBrigitte — APPROVED** [review]
`Logger` is actually never used and could be removed to simplify things. But other than that fine with me.

**Review by QuentinBisson — COMMENTED** [review]
Does that mean we can remove this resource entirely now if it was deployed everywhere?

**Comment by mcbenjemaa** [comment]
PMO was released,  which means next we can merge #1040 that will cleanup the actual code.

**Comment by QuentinBisson** [comment]
LOVE IT

**Pull request merged**
