### PR TITLE
refactor: remove service monitor resource

### PR DESCRIPTION
**Pull request by QuentinBisson**
Remove the service monitor resource as all the servicemonitor cr have been removed.

## Checklist

I have:

- [x] Described why this change is being introduced
- [x] Separated out refactoring/reformatting in a dedicated PR
- [x] Updated changelog in `CHANGELOG.md`

### CODE REVIEW

**Comment by mig4** [comment]
This makes me cry 😭

**Comment by QuentinBisson** [comment]
Why is that?

**Comment by mig4** [comment]
> Why is that?

I abhor templating YAML to generate data structures, it's error prone, it's hard to read, to avoid duplication you have to use text-based includes which are not obvious where they come from and have no concept of the overall config structure. Using native objects like `ServiceMonitor` would've been so much better.

Well, fortunately if we want PMO to be useful upstream we'll need to separate all this out and address this anyway, so I'm still hopeful 😉

**Review by TheoBrigitte — APPROVED** [review]
Let it go in peace, but might bring it back some time in the future @mig4

**Comment by QuentinBisson** [comment]
@mig4 I know this was not directed at me and thanks for explaining :D
I think we should contribute https://github.com/prometheus-operator/prometheus-operator/issues/2787 to actually achieve that :D

**Pull request merged**
