### PR TITLE
Add SLO classes to SLO alerts

### PR DESCRIPTION
**Pull request by QuentinBisson**
Adding slo classes that were only added to g8s-prometheus

### CODE REVIEW

**Comment by JosephSalisbury** [comment]
I don't get this. What's it do?

**Comment by omegas27** [comment]
This is just updating the service level rules to those in g8s-prometheus as classes were added but in g8s-prometheus and not in pmo.
Also, I removed useless label_replace as those were used for exported_cluster_id which is not used anymore

**Comment by JosephSalisbury** [comment]
my concern is we didn't finish those slo classes at all, so i'm not sure if they're ready to yet to port, i don't think we even tested that PR up in g8s-prom

**Comment by omegas27** [comment]
Well, we might have an issue as this is merged and released

**Comment by JosephSalisbury** [comment]
I was talking about https://github.com/giantswarm/g8s-prometheus/pull/1149

**Comment by omegas27** [comment]
The only ones I updated are from https://github.com/giantswarm/g8s-prometheus/blob/master/helm/g8s-prometheus/prometheus-recording-rules/service-level.rules.yml which is merged in master The PR you linked is mostly removing the cluster_type which I am not. We can leave this one open for now as well though if you prefer

**Pull request closed without merging**
