### PR TITLE
Add metric relabel config for KMS

### PR DESCRIPTION
**Pull request by QuentinBisson**
## Checklist

I have:

- [x] Described why this change is being introduced
- [x] Separated out refactoring/reformatting in a dedicated PR
- [ x] Updated changelog in `CHANGELOG.md`

### CODE REVIEW

**Comment by tomahawk28** [comment]
Can you test this? I think at least you should see the metrics with labels, workload_name.

**Comment by QuentinBisson** [comment]
I am testing it :D

**Comment by QuentinBisson** [comment]
Tested on ginger: 
image

**Review by rossf7 — APPROVED** [review]
LGTM

**Pull request merged**
