### PR TITLE
Do not reconcile service monitors in CAPO MCs

### PR DESCRIPTION
**Pull request by QuentinBisson**
Towards https://github.com/giantswarm/giantswarm/issues/23130

## Checklist

I have:

- [x] Described why this change is being introduced
- [x] Separated out refactoring/reformatting in a dedicated PR
- [x] Updated changelog in `CHANGELOG.md`

### CODE REVIEW

**Review by mcbenjemaa — APPROVED** [review]
LGTM

**Review by mcbenjemaa — COMMENTED** [review]
What about WC Prometheus?

**Comment by QuentinBisson** [comment]
WC prometheus is not using service monitors

**Comment by QuentinBisson** [comment]
After the change:
image

**Pull request merged**
