### PR TITLE
change CAPI version from v1alpha3 to v1beta1

### PR DESCRIPTION
**Pull request by TheoBrigitte**

### CODE REVIEW

**Comment by QuentinBisson** [comment]
@TheoBrigitte what do we need to  make it ready for review ?

**Comment by TheoBrigitte** [comment]
> @TheoBrigitte what do we need to make it ready for review ?

We need to make sure this works on every installations.

**Comment by QuentinBisson** [comment]
Tested on Gauss, Gunther and Gubble 🚀

**Review by QuentinBisson — APPROVED** [review]

**Comment by QuentinBisson** [comment]
Tested on Azure also

**Comment by TheoBrigitte** [comment]
Does this means that `v1alpha3` is just gone everywhere ?

**Comment by QuentinBisson** [comment]
All clusters are stored in v1beta1 so yes :)

**Comment by QuentinBisson** [comment]
Closes https://github.com/giantswarm/giantswarm/issues/23229

**Comment by nprokopic** [comment]
You might also want to bump `sigs.k8s.io/cluster-api` module version to v1.1.5.

**Review by nprokopic — APPROVED** [review]
:tada:

**Comment by QuentinBisson** [comment]
I had to revert 1.1.5 because we support 1.18 in PMO still (i.e. buffalo)

**Review by QuentinBisson — APPROVED** [review]

**Pull request merged**
