### PR TITLE
prometheus-agent: increase max samples per send

### PR DESCRIPTION
**Pull request by hervenicol**
Towards https://github.com/giantswarm/giantswarm/issues/25049

For prometheus-agent remotewrite to work fine, it has to send data in rather big batches.
The previous batch size was too small, let's increase it.

I have to understand the deployment procedure before merging it. I'll probably add stuff in the CHANGELOG when I test it.

## Checklist

I have:

- [x] Described why this change is being introduced
- [ ] Separated out refactoring/reformatting in a dedicated PR
- [x] Updated changelog in `CHANGELOG.md`

### CODE REVIEW

**Comment by hervenicol** [comment]
App gets deployed correctly, with no error.

Then, secrets named `[cluster]-remote-write-api-endpoint-config` are not updated, because immutable, but it looks like this does not generate errors. Actually, I think PMO does not even try to update these resources when already existing.
But if I delete one, it is then re-created (after a few minutes) with the new settings.

So, I think there's nothing preventing from releasing this change, then look for the best way to recycle these secrets.
At least, that would give a way to change and persist settings on installations that have problems with prometheus-agent.

**Review by TheoBrigitte — APPROVED** [review]
Sounds legit. I think we should document why this secret is immutable, but not necessarily in this PR.

**Comment by hervenicol** [comment]
> Sounds legit. I think we should document why this secret is immutable, but not necessarily in this PR.

I guess @QuentinBisson or @mcbenjemaa have more context on this?
But I agree: not this PR's problem :grin:

**Comment by QuentinBisson** [comment]
FYI it is immutable because we decided that the api key for the remote write endpoint secret should not change on every reconciliation so making it immutable made sense (because we should technically not change it) but we can definitly make it an Opaque secret so we can change the queueConfig

**Pull request merged**
