### PR TITLE
Handling upstream code via `git subtree`

### PR DESCRIPTION
**Pull request by TheoBrigitte**
This PR aims at better handling the upstream code we have copied over from [alertmanager@v0.21.0](https://github.com/prometheus/alertmanager/tree/v0.21.0/config) and [prometheus common@v0.17.0](https://github.com/prometheus/common/tree/v0.17.0/config).

Here is the git magic I used:
```
$ git checkout -b upstream-code

# remove the code copied over
$ git rm -r pkg/alertmanager/config/
$ git commit -am "remove alertmanager/config copy"
$ git rm -r pkg/prometheus/common/config/
$ git commit -am "remove prometheus/common/config copy"

# add alertmanager/config@v0.21.0
$ git remote add -f alertmanager https://github.com/prometheus/alertmanager.git
$ git checkout v0.21.0
$ git subtree split -P config/ -b alertmanager-config
$ git checkout upstream-code
$ git subtree add --squash -P pkg/alertmanager/config alertmanager-config

# cleanup all local tags, because some are overlapping
$ git tag -d $(git tag -l)

# add prometheus/common/config@v0.17.0
$ git remote add -f common https://github.com/prometheus/common.git
$ git checkout v0.17.0
$ git subtree split -P config/ -b common-config
$ git checkout upstream-code
$ git subtree add --squash -P pkg/prometheus/common/config common-config

# restore our changes
$ git checkout origin/master -- pkg/alertmanager/config pkg/prometheus/common/config/
# commit changes
# also had to manually remove the deleted tests files

# restore local tags from PMO
$ git tag -d $(git tag -l)
$ git fetch origin
```

This was a lot of git magic for 0 changes in the end because it worked :)
But I learned how to handle this copied code with `git subtree` and shared this in the README, so it makes our lives easier in the future when having to deal with this hopefully.

## Checklist

I have:

- [x] Described why this change is being introduced
- [x] Separated out refactoring/reformatting in a dedicated PR
- [x] Updated changelog in `CHANGELOG.md`

### CODE REVIEW

**Comment by TheoBrigitte** [comment]
gitleaks is not happy, but those are false positive leaks from upstream test and I will gladly ignore this as this will all be squashed when merged.

**Comment by QuentinBisson** [comment]
This is nice :D Hopefully, once the upstream PR is merged for the authorization to opsgenie, we will not need this code anymore

**Review by QuentinBisson — APPROVED** [review]

**Comment by TheoBrigitte** [comment]
> This is nice :D Hopefully, once the upstream PR is merged for the authorization to opsgenie, we will not need this code anymore

I thought we only have `alertmanager/config` and `common/config` copied over to fix how secret are generated in the alertmanager config. Did we copy something else ? Let's document this

**Comment by QuentinBisson** [comment]
Not yet but using the prometheus operator managed alertmanager means we do not need to hack g8s-prometheus alertmanager config as the alertmanagerconfig CR are used to manage this

**Comment by TheoBrigitte** [comment]
> the alertmanagerconfig

Alright :+1:

**Review by mig4 — APPROVED** [review]

**Pull request merged**
