### PR TITLE
Add term to not count api-server errors for transitioning clusters

### PR DESCRIPTION
**Pull request by anvddriesch**
Towards https://github.com/giantswarm/giantswarm/issues/17638

The goal here is to not count api-server errors while a cluster is transitioning so that we do not eat up the error budget and get false positives once the transition is complete.
Note that this will not make a difference for workload-clusters until the cluster-status metrics are fixed by atlas.

## Checklist

I have:

- [ ] Described why this change is being introduced
- [ ] Separated out refactoring/reformatting in a dedicated PR
- [ ] Updated changelog in `CHANGELOG.md`

### CODE REVIEW

**Review by njuettner — APPROVED** [review]
lgtm if that works 🙂

**Review by TheoBrigitte — COMMENTED** [review]
Why no using inhibitions instead of complex expression for this ?

**Comment by JosephSalisbury** [comment]
What about for HA masters? It feels weird to not have them alert if there's issues during upgrade

**Comment by anvddriesch** [comment]
Right now we use the inhibition during upgrades but it feels wrong. We are still counting the errors and it still counts towards the error budget even though it is an expected downtime.
I have not considered the HA Masters clusters separately since we currently don't (inhibition works for everything). Maybe I can come up with something.

**Review by calvix — APPROVED** [review]
that looks fancy , never seen ignoring() before

**Comment by anvddriesch** [comment]
While this is not perfect I want to try it out for now and iterate once the inhibition issue is resolved

**Pull request merged**
