### PR TITLE
add logging to debug issue with already existing cilium netpols

### PR DESCRIPTION
**Pull request by QuantumEnigmaa**
This PR aims to fix the current issue with PMO which throws error when a ciliumnetpol already exist for prometheus on the MC. Example log : 
```
{"caller":"github.com/giantswarm/micrologger@v1.1.1/logger.go:88","controller":"prometheus-meta-operator-cluster-api-controller","event":"update","level":"error","loop":"186","message":"retrying due to error","object":"org-adidas/deu01","resource":"ciliumnetpol","stack":{"annotatio
n":"ciliumnetworkpolicies.cilium.io \"deu01-prometheus\" already exists","kind":"unknown","stack":[{"file":"/root/project/service/controller/resource/ciliumnetpol/create.go","line":31},{"file":"/go/pkg/mod/github.com/giantswarm/operatorkit/v7@v7.2.0/pkg/resource/wrapper/retryresour
ce/basic_resource.go","line":52}]},"time":"2024-02-12T14:59:38.510872+00:00","version":"1684122888"} 
```

## Checklist

I have:

- [x] Described why this change is being introduced
- [ ] Separated out refactoring/reformatting in a dedicated PR
- [x] Updated changelog in `CHANGELOG.md`

### CODE REVIEW

**Comment by QuantumEnigmaa** [comment]
So as expected, with the current code implementation, PMO is not able to retrieve the existing ciliumnetpol and thus always goes through the create process : 
```
ciliumnetpol: (*unstructured.Unstructured)(nil)
```

**Comment by QuantumEnigmaa** [comment]
Ok now it's working : 
```
"ciliumnetpol: &unstructured.Unstructured{Object:map[string]interface {}{\"apiVersion\":\"cilium.io/v2\", \"kind\":\"CiliumNetworkPolicy\", \"metadata\":map[string]interface {}{\"creationTimestamp\":\"2024-02-12T11:27:35Z\", \"generation\":1, \"labels\":map[string]interface {}{\"app.kubernetes.io/name\":\"prometheus\"}, \"managedFields\":[]interface {}{map[string]interface {}{\"apiVersion\":\"cilium.io/v2\", \"fieldsType\":\"FieldsV1\", \"fieldsV1\":map[string]interface {}{\"f:metadata\":map[string]interface {}{\"f:labels\":map[string]interface {}{\".\":map[string]interface {}{}, \"f:app.kubernetes.io/name\":map[string]interface {}{}}}, \"f:spec\":map[string]interface {}{\".\":map[string]interface {}{}, \"f:egress\":map[string]interface {}{}, \"f:endpointSelector\":map[string]interface {}{\".\":map[string]interface {}{}, \"f:matchLabels\":map[string]interface {}{\".\":map[string]interface {}{}, \"f:app.kubernetes.io/name\":map[string]interface {}{}}}, \"f:ingress\":map[string]interface {}{}}}, \"manager\":\"prometheus-meta-operator\", \"operation\":\"Update\", \"time\":\"2024-02-12T11:27:35Z\"}}, \"name\":\"gaia-prometheus\", \"namespace\":\"gaia-prometheus\", \"resourceVersion\":\"1535619116\", \"uid\":\"3591c98d-1b31-4d44-b36d-33a70e5c200b\"}, \"spec\":map[string]interface {}{\"egress\":[]interface {}{map[string]interface {}{\"toEntities\":[]interface {}{\"kube-apiserver\", \"cluster\"}}, map[string]interface {}{\"toEntities\":[]interface {}{\"world\"}, \"toPorts\":[]interface {}{map[string]interface {}{\"ports\":[]interface {}{map[string]interface {}{\"port\":\"443\"}, map[string]interface {}{\"port\":\"6443\"}}}}}}, \"endpointSelector\":map[string]interface {}{\"matchLabels\":map[string]interface {}{\"app.kubernetes.io/name\":\"prometheus\"}}, \"ingress\":[]interface {}{map[string]interface {}{\"fromEntities\":[]interface {}{\"cluster\"}, \"toPorts\":[]interface {}{map[string]interface {}{\"ports\":[]interface {}{map[string]interface {}{\"port\":\"9090\"}}}}}}}}}"
```

**Comment by QuantumEnigmaa** [comment]
@marieroque normally it should be safe to merge and realease :angel:

**Review by QuentinBisson — APPROVED** [review]
Let's go

**Pull request merged**
