### PR TITLE
add .svc suffix to alertmanager target

### PR DESCRIPTION
**Pull request by bavarianbidi**
To make PMO work behind a corporate proxy, we have to inject the `HTTP_PROXY`, `HTTPS_PROXY` and `NO_PROXY` variable.

To keep the `NO_PROXY` list as "simple" as possible, following in-cluster-specific values are configured:
`<baseDomain>,<podCIDRBlock>,<serviceCIDRBlock>,<external_k8s_API_IP>`. 

To not change every application to make use of the FQDN (as `baseDomain` could differ) i've decided to add `svc` to the `NO_PROXY` list.

The change of the scrape-target from `alertmanager-operated.monitoring` to `alertmanager-operated.monitoring.svc`  a no op for all existing clusters.

towards: https://github.com/giantswarm/roadmap/issues/1423
xref: https://github.com/giantswarm/silence-operator/pull/231

## Checklist

I have:

- [x] Described why this change is being introduced
- [ ] Separated out refactoring/reformatting in a dedicated PR
- [x] Updated changelog in `CHANGELOG.md`

### CODE REVIEW

**Review by mcbenjemaa — APPROVED** [review]

**Comment by mcbenjemaa** [comment]
We need to fix the build

**Comment by bavarianbidi** [comment]
> We need to fix the build

see PR https://github.com/giantswarm/prometheus-meta-operator/pull/1011

**Review by QuentinBisson — APPROVED** [review]
LGTM when tested

**Comment by bavarianbidi** [comment]
> LGTM when tested

@QuentinBisson :shrug: who should test? because of your comment [below](https://github.com/giantswarm/prometheus-meta-operator/pull/1010#issuecomment-1274601078) i thought you are testing this :sweat_smile:

**Comment by QuentinBisson** [comment]
I'll test, sorry I forgot :D

**Pull request merged**
