### PR TITLE
Drop highest cardinality nginx metrics

### PR DESCRIPTION
**Pull request by mig4**
Reduced number of metrics ingested from nginx-ingress-controller in order to
reduce memory requirements of Prometheus.

Closes: https://github.com/giantswarm/giantswarm/issues/14660

### CODE REVIEW

**Review by JosephSalisbury — APPROVED** [review]

**Comment by mig4** [comment]
Tested on _anteater_.

Numbers of metrics by job name, before:

```
{job="hype1-prometheus/managed-app-hype1/0"}	167966
{job="hype1-prometheus/node-exporter-hype1/0"}	36432
{job="hype1-prometheus/kube-state-metrics-hype1/0"}	31045
{job="hype1-prometheus/kubernetes-apiserver-hype1/0"}	21485
{job="hype1-prometheus/cadvisor-hype1/0"}	17348
{job="hype1-prometheus/kubelet-hype1/0"}	16695
{job="hype1-prometheus/coredns-hype1/0"}	4388
{job="hype1-prometheus/aws-node-hype1/0"}	2930
{job="hype1-prometheus/kube-proxy-hype1/0"}	2230
{job="hype1-prometheus/net-exporter-hype1/0"}	2168
{job="hype1-prometheus/calico-node-hype1/0"}	1903
{job="hype1-prometheus/kubernetes-controller-manager-hype1/0"}	1452
{job="hype1-prometheus/etcd-hype1/0"}	1252
{job="hype1-prometheus/kubernetes-scheduler-hype1/0"}	1237
{job="hype1-prometheus/cluster-autoscaler-hype1/0"}	772
{job="hype1-prometheus/cert-exporter-hype1/0"}	652
{job="hype1-prometheus/chart-operator-hype1/0"}	279
{job="hype1-prometheus/docker-hype1/0"}	84
{}	2
```

after:

```
{job="hype1-prometheus/node-exporter-hype1/0"}	36432
{job="hype1-prometheus/kube-state-metrics-hype1/0"}	31045
{job="hype1-prometheus/managed-app-hype1/0"}	29647
{job="hype1-prometheus/kubernetes-apiserver-hype1/0"}	21485
{job="hype1-prometheus/cadvisor-hype1/0"}	17348
{job="hype1-prometheus/kubelet-hype1/0"}	16695
{job="hype1-prometheus/coredns-hype1/0"}	4388
{job="hype1-prometheus/aws-node-hype1/0"}	2930
{job="hype1-prometheus/kube-proxy-hype1/0"}	2230
{job="hype1-prometheus/net-exporter-hype1/0"}	2168
{job="hype1-prometheus/calico-node-hype1/0"}	1903
{job="hype1-prometheus/kubernetes-controller-manager-hype1/0"}	1452
{job="hype1-prometheus/etcd-hype1/0"}	1252
{job="hype1-prometheus/kubernetes-scheduler-hype1/0"}	1237
{job="hype1-prometheus/cluster-autoscaler-hype1/0"}	772
{job="hype1-prometheus/cert-exporter-hype1/0"}	652
{job="hype1-prometheus/chart-operator-hype1/0"}	279
{job="hype1-prometheus/docker-hype1/0"}	84
{}	2
```

**Comment by JosephSalisbury** [comment]
fyi @piontec @giantswarm/team-batman @giantswarm/team-halo, this is a superset of what nginx metrics we're keeping in the old setup, let's talk in future if you need one of these metrics specifically

**Comment by omegas27** [comment]
Would it make sense to have a dashboard for the number of exported metrics per job in cortex?

**Comment by JosephSalisbury** [comment]
@omegas27 yes see https://github.com/giantswarm/giantswarm/issues/14424

**Pull request merged**
