### PR TITLE
add remoteWrite CRD to helm chart

### PR DESCRIPTION
**Pull request by hervenicol**
Towards https://github.com/giantswarm/roadmap/issues/1109

Deploy remoteWrite CRD with Helm chart.

## Checklist

I have:

- [x] Described why this change is being introduced
- [ ] Separated out refactoring/reformatting in a dedicated PR
- [x] Updated changelog in `CHANGELOG.md`

### CODE REVIEW

**Comment by hervenicol** [comment]
Deployment tested on Gauss:
```
$ opsctl deploy -i gauss prometheus-meta-operator@deploy-remoteWrite-CRD
[...]
$ k get crd | grep remote
remotewrites.monitoring.giantswarm.io                            2022-05-30T08:14:03Z
$
```

**Comment by hervenicol** [comment]
> I guess we agreed to put the CRD in a [separate chart](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-2-separate-charts)

I and @TheoBrigitte  understood quite the opposite, as you can read in the issue comments :rofl: 
https://github.com/giantswarm/roadmap/issues/1109#issuecomment-1139518287

@TheoBrigitte, can you please confirm/deny?

**Comment by mcbenjemaa** [comment]
My bad, I just understood that Nikola suggests putting the CRD in a separate chart and then making it a dependency on the pmo chart.

**Comment by TheoBrigitte** [comment]
As we are not installing any `RemoteWrite` CR in this chart, we are safe to install the `RemoteWrite` CRD as a regular resource here.

**Review by mcbenjemaa — APPROVED** [review]
LGTM

**Review by TheoBrigitte — APPROVED** [review]

**Pull request merged**
