### PR TITLE
Update prom to 2.28.1

### PR DESCRIPTION
**Pull request by QuentinBisson**
Upgrading prometheus to the latest version

## Checklist

I have:

- [x] Described why this change is being introduced
- [x] Separated out refactoring/reformatting in a dedicated PR
- [x] Updated changelog in `CHANGELOG.md`

### CODE REVIEW

**Review by JosephSalisbury — APPROVED** [review]
lgtmiiwfy - do we need to coordinate this w/ prometheus-operator version?

**Review by mig4 — APPROVED** [review]
Ditto.

**Comment by mig4** [comment]
> do we need to coordinate this w/ prometheus-operator version?

It seems there's usually enough compatibility there that it works OK without it, but yeah it's not a supported configuration, so it would be good to update _prometheus-operator_ to 0.49.0 (see https://github.com/prometheus-operator/prometheus-operator/blob/master/pkg/operator/defaults.go).

**Comment by QuentinBisson** [comment]
I am planning on testing it first anyway :) But we can ask Halo to update the app

**Pull request merged**
