### PR TITLE
Remove per provider app alerts for cluster-autoscaler

### PR DESCRIPTION
**Pull request by rossf7**
Towards https://github.com/giantswarm/giantswarm/issues/14846

app-exporter 0.3.0 was released earlier. It adds provider support so the per provider alerts for cluster-autoscaler are no longer needed.

## Checklist

I have:

- [x] Described why this change is being introduced
- [ ] Separated out refactoring/reformatting in a dedicated PR
- [x] Updated changelog in `CHANGELOG.md`

### CODE REVIEW

**Comment by QuentinBisson** [comment]
Is there not an exception in the batman rule to not alert on the cluster-operator in WorkloadClusterAppFailed?

Also, the Azure rules are duplicated in azure.management-cluster.yml. Could you also remove them?

**Comment by rossf7** [comment]
> Is there not an exception in the batman rule to not alert on the cluster-operator in WorkloadClusterAppFailed?

@QuentinBisson Thanks I missed that. Done.

> Also, the Azure rules are duplicated in azure.management-cluster.yml. Could you also remove them?

Also removed these. 👍

**Comment by QuentinBisson** [comment]
THank you :)

**Review by QuentinBisson — APPROVED** [review]
LGTM. Can you test it on an installation first though?

**Comment by rossf7** [comment]
Tested on gauss. I also added ManagementClusterAppFailedLudacris as it was missing.

@QuentinBisson There is another change I need to make to assign alerts to Halo but still route to #alert-batman.

Will do a separate PR after lunch but hold off merging this till its done.

**Review by tomahawk28 — APPROVED** [review]

**Comment by QuentinBisson** [comment]
@rossf7 I;m not sure where we are with this one. I'm currently moving out the rules to https://github.com/giantswarm/prometheus-rules so I will close this PR. Can you open it there if this is still needed?

**Comment by rossf7** [comment]
@QuentinBisson No problem with closing. Sorry I lost track of this PR. 

I have team oncall on Monday so will check then and do a fresh PR if its still needed.

**Pull request closed without merging**
