### PR TITLE
add managed-app/crsync target

### PR DESCRIPTION
**Pull request by TheoBrigitte**
Towards: https://github.com/giantswarm/giantswarm/issues/11723

Tested ...

on `gauss`

image

on `gorilla`

image

### CODE REVIEW

**Review by omegas27 — COMMENTED** [review]
This might overlap with some of our existing targets

**Comment by TheoBrigitte** [comment]
> This might overlap with some of our existing targets

Yes there's a potential overlap, but that's the current setup we have. And targets are already overlapping

image

image

How about we exclude target with `giantswarm.io/monitoring` label from other targets?

**Comment by omegas27** [comment]
It would make sense that we drop them if we have the label

**Comment by TheoBrigitte** [comment]
> them

Ok, I'll do that in next PR then.

**Review by omegas27 — APPROVED** [review]

**Pull request merged**
