### PR TITLE
firecracker-improve-pod-stuck-aws

### PR DESCRIPTION
**Pull request by calvix**
towards https://github.com/giantswarm/giantswarm/issues/15617

add back alerts about pod stuck to relevant components for firecracker

## Checklist

I have:

- [x] Described why this change is being introduced
- [ ] Separated out refactoring/reformatting in a dedicated PR
- [x] Updated changelog in `CHANGELOG.md`

### CODE REVIEW

**Review by QuentinBisson — CHANGES_REQUESTED** [review]
Do you mind adding exceptions https://github.com/giantswarm/prometheus-meta-operator/blob/ec63a0f409d0f2b34d1a45729e44411103fee387/helm/prometheus-meta-operator/templates/prometheus-rules/management-cluster.rules.yml#L14 for the biscuit alerts then?

**Comment by calvix** [comment]
> Do you mind adding exceptions
> 
> https://github.com/giantswarm/prometheus-meta-operator/blob/ec63a0f409d0f2b34d1a45729e44411103fee387/helm/prometheus-meta-operator/templates/prometheus-rules/management-cluster.rules.yml#L14
> for the biscuit alerts then?

that is a little bit hard as  cluster-operator and vertical-pod-autoscaler can run on different providers and if I set the exception for them then on other providers nobody will get the alert

**Comment by QuentinBisson** [comment]
Should it not be split per provider in that case at least for cluster operator? Also, why are you taking ownership of the vertical pod autoscaler?

**Comment by QuentinBisson** [comment]
Technically, you can just add the alert for celestial in azure.management-cluster.rules.yaml for azure-operator and cluster operator and add those as exception in the biscuti rule as rocket is taking care of kvm managment clusters

**Review by QuentinBisson — APPROVED** [review]
Thanks :D

**Comment by calvix** [comment]
@giantswarm/team-celestial you ok with this? Just adding a alert for you that will page incase azure operator or cluster operator will be stuck in pending on azure MC

**Review by whites11 — APPROVED** [review]
LGTMIIWFY

**Pull request merged**
