### PR TITLE
Remove azure provider

### PR DESCRIPTION
**Pull request by QuentinBisson**
This PR removes the now deleted Azure Provider from PMO

## Checklist

I have:

- [x] Described why this change is being introduced
- [x] Separated out refactoring/reformatting in a dedicated PR
- [x] Updated changelog in `CHANGELOG.md`

### CODE REVIEW

**Comment by hervenicol** [comment]
I guess there's also some stuff to be cleaned up here: https://github.com/giantswarm/prometheus-meta-operator/blob/master/pkg/cluster/types.go
and here: https://github.com/giantswarm/prometheus-meta-operator/blob/master/service/key/key.go#L121

**Comment by QuentinBisson** [comment]
Nope the 2 links are for CAPZ

**Comment by hervenicol** [comment]
ooh, right! LGTM then! :+1:

**Review by hervenicol — APPROVED** [review]

**Comment by QuentinBisson** [comment]
I rebased :)

**Pull request merged**
