### PR TITLE
Fix(16537) Prometheus Storage alert

### PR DESCRIPTION
**Pull request by QuentinBisson**
Towards https://github.com/giantswarm/giantswarm/issues/16537
Closes https://github.com/giantswarm/giantswarm/issues/15871

## Checklist

I have:

- [x] Described why this change is being introduced
- [x] Separated out refactoring/reformatting in a dedicated PR
- [x] Updated changelog in `CHANGELOG.md`

### CODE REVIEW

**Comment by QuentinBisson** [comment]
Tested on gauss:
image

**Comment by JosephSalisbury** [comment]
Could you write a little about _why_ we need this? I don't follow it

**Comment by QuentinBisson** [comment]
We had only one alert related to storage space too low on the management cluster that was paging biscuit for the prometheus containers.
We splitted the alert using prometheus in the mountpoint but it was not sufficient as the alert was paging both biscuit and atlas.

This PR will fix this situation by alerting atlas for prometheus volumes and biscuit for the rest

**Review by JosephSalisbury — APPROVED** [review]

**Comment by JosephSalisbury** [comment]
gotcha, i'd be missed the difference in priority class matching

**Pull request merged**
