### PR TITLE
Add NoHealthyJumphost alert

### PR DESCRIPTION
**Pull request by QuentinBisson**
Add the NoHealthyJumphost once https://github.com/giantswarm/giantswarm/issues/15441 is resolved

### CODE REVIEW

**Review by TheoBrigitte — COMMENTED** [review]
Will this alert always fails then ?

**Comment by QuentinBisson** [comment]
As long as we do not allow access to the other bastion yes

**Comment by JosephSalisbury** [comment]
blocked by https://github.com/giantswarm/giantswarm/issues/15441 (for linking)

**Comment by JosephSalisbury** [comment]
lol, i should read descriptions~

**Comment by QuentinBisson** [comment]
Unblocked

**Pull request merged**
