### PR TITLE
Add batman alerts

### PR DESCRIPTION
**Pull request by QuentinBisson**
Towards **https://github.com/giantswarm/giantswarm/issues/15513 Move Managed Apps alerts to PMO**
This PR adds batman alerts to PMO

## Checklist

I have:

- [x] Described why this change is being introduced
- [x] Separated out refactoring/reformatting in a dedicated PR
- [x] Updated changelog in `CHANGELOG.md`

### CODE REVIEW

**Review by TheoBrigitte — COMMENTED** [review]
Cant review this really, this was done via `transform-rules` tool right ?

**Comment by QuentinBisson** [comment]
Yes, this was done using the tool but I had to do some changes with the renaming. I was trying to diff the tools result with the change but @JosephSalisbury distracted me on slack :D

**Comment by QuentinBisson** [comment]
```diff
colordiff /home/quentin/Documents/code/g8s-prometheus/tool/transform-rules/files helm/prometheus-meta-operator/templates/prometheus-rules
Only in helm/prometheus-meta-operator/templates/prometheus-rules: alertmanager.rules.yml
diff /home/quentin/Documents/code/g8s-prometheus/tool/transform-rules/files/app.rules.yml helm/prometheus-meta-operator/templates/prometheus-rules/app.rules.yml
6a7
>     cluster_type: "management_cluster"
7a9
>   namespace: '{{ include "resource.default.namespace" . }}'
12c14
<     - alert: ControlPlaneAppFailed
---
>     - alert: ManagementClusterAppFailed
14c16
<         description: '{{`Control Plane App {{ $labels.name }}, version {{ $labels.version }} is {{if $labels.status }} in {{ $labels.status }} state. {{else}} not installed. {{end}}`}}'
---
>         description: '{{`Management Cluster App {{ $labels.name }}, version {{ $labels.version }} is {{if $labels.status }} in {{ $labels.status }} state. {{else}} not installed. {{end}}`}}'
28c30
<     - alert: TenantAppFailed
---
>     - alert: WorkloadClusterAppFailed
30c32
<         description: '{{`Tenant App {{ $labels.name }}, version {{ $labels.version }} is {{if $labels.status }} in {{ $labels.status }} state. {{else}} not installed. {{end}}`}}'
---
>         description: '{{`Workload Cluster App {{ $labels.name }}, version {{ $labels.version }} is {{if $labels.status }} in {{ $labels.status }} state. {{else}} not installed. {{end}}`}}'
Only in helm/prometheus-meta-operator/templates/prometheus-rules: calico.rules.yml
Only in helm/prometheus-meta-operator/templates/prometheus-rules: certificate.all.rules.yml
Only in helm/prometheus-meta-operator/templates/prometheus-rules: certificate.management-cluster.rules.yml
Only in /home/quentin/Documents/code/g8s-prometheus/tool/transform-rules/files: certificate.rules.yml
diff /home/quentin/Documents/code/g8s-prometheus/tool/transform-rules/files/cert-manager.rules.yml helm/prometheus-meta-operator/templates/prometheus-rules/cert-manager.rules.yml
7a8
>   namespace: '{{ include "resource.default.namespace" . }}'
12c13
<     - alert: PodHighMemoryUsage
---
>     - alert: CertManagerPodHighMemoryUsage
diff /home/quentin/Documents/code/g8s-prometheus/tool/transform-rules/files/chart.rules.yml helm/prometheus-meta-operator/templates/prometheus-rules/chart.rules.yml
7a8
>   namespace: '{{ include "resource.default.namespace" . }}'
Only in helm/prometheus-meta-operator/templates/prometheus-rules: cluster.rules.yml
Only in helm/prometheus-meta-operator/templates/prometheus-rules: cluster-service.rules.yml
diff /home/quentin/Documents/code/g8s-prometheus/tool/transform-rules/files/configmap.rules.yml helm/prometheus-meta-operator/templates/prometheus-rules/configmap.rules.yml
7a8
>   namespace: '{{ include "resource.default.namespace" . }}'
16c17
<       expr: sum(kube_configmap_info{cluster_type="tenant_cluster",namespace="giantswarm",configmap=~".+\\.v.+"}) by (cluster_id) > 1000 or sum(kube_configmap_info{cluster_type="control_plane",namespace="kube-system",configmap=~".+\\.v.+"}) by (cluster_id) > 1000
---
>       expr: sum(kube_configmap_info{cluster_type="workload_cluster",namespace="giantswarm",configmap=~".+\\.v.+"}) by (cluster_id) > 1000 or sum(kube_configmap_info{cluster_type="management_cluster",namespace="kube-system",configmap=~".+\\.v.+"}) by (cluster_id) > 1000
Only in helm/prometheus-meta-operator/templates/prometheus-rules: crsync.rules.yml
Only in helm/prometheus-meta-operator/templates/prometheus-rules: daemonset.rules.yml
Only in helm/prometheus-meta-operator/templates/prometheus-rules: deployment.management-cluster.rules.yml
Only in /home/quentin/Documents/code/g8s-prometheus/tool/transform-rules/files: deployment.rules.yml
Only in helm/prometheus-meta-operator/templates/prometheus-rules: deployment.workload-cluster.rules.yml
Only in helm/prometheus-meta-operator/templates/prometheus-rules: draughtsman.rules.yml
diff /home/quentin/Documents/code/g8s-prometheus/tool/transform-rules/files/elasticsearch.rules.yml helm/prometheus-meta-operator/templates/prometheus-rules/elasticsearch.rules.yml
7a8
>   namespace: '{{ include "resource.default.namespace" . }}'
Only in helm/prometheus-meta-operator/templates/prometheus-rules: etcd.rules.yml
diff /home/quentin/Documents/code/g8s-prometheus/tool/transform-rules/files/external-dns.rules.yml helm/prometheus-meta-operator/templates/prometheus-rules/external-dns.rules.yml
7a8
>   namespace: '{{ include "resource.default.namespace" . }}'
Only in helm/prometheus-meta-operator/templates/prometheus-rules: fluentbit.rules.yml
Only in helm/prometheus-meta-operator/templates/prometheus-rules: gatekeeper.rules.yml
diff /home/quentin/Documents/code/g8s-prometheus/tool/transform-rules/files/helm.rules.yml helm/prometheus-meta-operator/templates/prometheus-rules/helm.rules.yml
7a8
>   namespace: '{{ include "resource.default.namespace" . }}'
diff /home/quentin/Documents/code/g8s-prometheus/tool/transform-rules/files/ingress-controller.rules.yml helm/prometheus-meta-operator/templates/prometheus-rules/ingress-controller.rules.yml
7a8
>   namespace: '{{ include "resource.default.namespace" . }}'
66c67
<       expr: avg(ingress_controller_ssl_expire_time_seconds{cluster_type="control_plane",control_plane!~"(etcd|api).*"}) without (instance) < (time() + (10 * 24 * 3600))
---
>       expr: avg(ingress_controller_ssl_expire_time_seconds{cluster_type="management_cluster",control_plane!~"(etcd|api).*"}) without (instance) < (time() + (10 * 24 * 3600))
Only in helm/prometheus-meta-operator/templates/prometheus-rules: inhibit.all.rules.yml
Only in helm/prometheus-meta-operator/templates/prometheus-rules: inhibit.management-cluster.rules.yml
diff /home/quentin/Documents/code/g8s-prometheus/tool/transform-rules/files/managed-apps-basic-sli.rules.yml helm/prometheus-meta-operator/templates/prometheus-rules/managed-apps-basic-sli.rules.yml
7a8
>   namespace: '{{ include "resource.default.namespace" . }}'
diff /home/quentin/Documents/code/g8s-prometheus/tool/transform-rules/files/managed-logging.rules.yml helm/prometheus-meta-operator/templates/prometheus-rules/managed-logging.rules.yml
7a8
>   namespace: '{{ include "resource.default.namespace" . }}'
Only in helm/prometheus-meta-operator/templates/prometheus-rules: management-cluster.rules.yml
diff /home/quentin/Documents/code/g8s-prometheus/tool/transform-rules/files/microendpoint.rules.yml helm/prometheus-meta-operator/templates/prometheus-rules/microendpoint.rules.yml
6a7
>     cluster_type: "management_cluster"
7a9
>   namespace: '{{ include "resource.default.namespace" . }}'
11a14,24
>     - alert: CollidingOperatorsAtlas
>       annotations:
>         description: '{{`CR version {{ $labels.version }} in cluster {{ $labels.cluster_id }} is reconciled by multiple apps including {{ $labels.app }}.`}}'
>         opsrecipe: multiple-operators-running-same-version/
>       expr: sum(label_replace(giantswarm_build_info{app=~"prometheus-meta-operator"}, "version", "$1", "reconciled_version", "(.+)")) by (app, cluster_id, version) > 1
>       for: 5m
>       labels:
>         area: empowerment
>         severity: page
>         team: atlas
>         topic: releng
diff /home/quentin/Documents/code/g8s-prometheus/tool/transform-rules/files/operatorkit.rules.yml helm/prometheus-meta-operator/templates/prometheus-rules/operatorkit.rules.yml
6a7
>     cluster_type: "management_cluster"
7a9
>   namespace: '{{ include "resource.default.namespace" . }}'
Only in helm/prometheus-meta-operator/templates/prometheus-rules: prometheus-meta-operator.rules.yml
Only in helm/prometheus-meta-operator/templates/prometheus-rules: prometheus.rules.yml
diff /home/quentin/Documents/code/g8s-prometheus/tool/transform-rules/files/secret.rules.yml helm/prometheus-meta-operator/templates/prometheus-rules/secret.rules.yml
7a8
>   namespace: '{{ include "resource.default.namespace" . }}'
Only in helm/prometheus-meta-operator/templates/prometheus-rules: systemd.rules.yml
diff /home/quentin/Documents/code/g8s-prometheus/tool/transform-rules/files/tiller.rules.yml helm/prometheus-meta-operator/templates/prometheus-rules/tiller.rules.yml
7a8
>   namespace: '{{ include "resource.default.namespace" . }}'
28c29
<       expr: chart_operator_tiller_reachable{cluster_type="tenant_cluster"} == 0
---
>       expr: chart_operator_tiller_reachable{cluster_type="workload_cluster"} == 0
Only in helm/prometheus-meta-operator/templates/prometheus-rules: up.all.rules.yml
Only in helm/prometheus-meta-operator/templates/prometheus-rules: up.management-cluster.rules.yml
Only in /home/quentin/Documents/code/g8s-prometheus/tool/transform-rules/files: up.rules.yml
Only in helm/prometheus-meta-operator/templates/prometheus-rules: vault.rules.yml
```

**Comment by JosephSalisbury** [comment]
i can only apologise :D

**Review by TheoBrigitte — APPROVED** [review]
Thanks for the diff, this looks all good!

**Comment by QuentinBisson** [comment]
@giantswarm/team-batman-engineers I added you here to take a quick look as well

**Comment by glitchcrab** [comment]
> @giantswarm/team-batman-engineers I added you here to take a quick look as well

also pinged team-halo-engineers as we share Batman's rotation :)

**Review by tomahawk28 — APPROVED** [review]

**Review by ced0ps — APPROVED** [review]
LGTM

**Review by rossf7 — APPROVED** [review]

**Pull request merged**
