### PR TITLE
supports prometheus-operator upgrade v0.54.0

### PR DESCRIPTION
**Pull request by mcbenjemaa**
Bump prometheus-operator to v0.54.0

## Checklist

I have:

- [X] Described why this change is being introduced
- [X] Separated out refactoring/reformatting in a dedicated PR
- [X] Updated changelog in `CHANGELOG.md`

### CODE REVIEW

**Review by TheoBrigitte — COMMENTED** [review]
Looks good, but CI throw some errors.

Also can you please test this. What should be checked is:

- Do we still have a Prometheus CR created and a server coming up when a cluster is created
- Is the Alertmanager config for heartbeat still created correctly when a cluster is created
- Is Alertmanager CR updated correctly and the server coming up
- RemoteWrite are also involved but you know better :)

**Comment by QuentinBisson** [comment]
Considering the errors in CI, merging this should fix the issue: https://github.com/giantswarm/prometheus-meta-operator/pull/839

**Comment by mcbenjemaa** [comment]
> Tested on ginger: (everything looks fine 🟢 )
> - Do we still have a Prometheus CR created and a server coming up when a cluster is created  ✅ 
> - Is the Alertmanager config for heartbeat still created correctly when a cluster is created ✅ 
> - Is Alertmanager CR updated correctly and the server coming up ✅ 
> - RemoteWrite are also involved but you know better :) ✅

**Review by QuentinBisson — APPROVED** [review]
LGTM

**Comment by mcbenjemaa** [comment]
Pending approval @TheoBrigitte

**Review by TheoBrigitte — APPROVED** [review]
Changes looks alright. Good for me when tested.

**Pull request merged**
