### PR TITLE
Add recording rules for kube-mixins

### PR DESCRIPTION
**Pull request by QuentinBisson**
Towards https://github.com/giantswarm/giantswarm/issues/13725
## Checklist

I have:

- [x] Described why this change is being introduced
- [x] Separated out refactoring/reformatting in a dedicated PR
- [x] Updated changelog in `CHANGELOG.md`

### CODE REVIEW

**Comment by QuentinBisson** [comment]
The new mixins require missing recording rules added in this PR

**Comment by JosephSalisbury** [comment]
How is the memory usage with these added?

**Comment by QuentinBisson** [comment]
I do not really see any changes:
image

**Comment by mig4** [comment]
A couple of questions:

1. What are _mixins_?
2. Where are these rules coming from? Did you write them?

**Comment by QuentinBisson** [comment]
Mixins are a set of grafana dashboards for kubernetes: https://github.com/kubernetes-monitoring/kubernetes-mixin

I took them and the rules from the kube-prometheus-stack project https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack/templates/grafana/dashboards-1.14

**Review by mig4 — APPROVED** [review]

**Pull request merged**
