### PR TITLE
Release v4.64.0

### PR DESCRIPTION
**Pull request by taylorbot**

### CODE REVIEW

**Review by AverageMarcus — APPROVED** [review]

**Comment by hervenicol** [comment]
We've had multiple issues recently with trivial changes in alertmanager config which broke alertmanager.
Are you sure you want to release this on a Friday afternoon?

**Comment by hervenicol** [comment]
I know there's not much change, but there's no verification /at all/ of alertmanager's config currently. So even trivial changes happened to break it. :grimacing: 

So yes, I think it's better if it waits until Monday.

**Comment by AverageMarcus** [comment]
@hervenicol You happy to have this released this morning?

**Review by hervenicol — APPROVED** [review]
Yes, fire! :rocket:

**Comment by AverageMarcus** [comment]
🚀 

Do I need to do anything to get it pushed out everywhere or is it automatic?

**Pull request merged**
