### PR TITLE
Adds revision history limit

### PR DESCRIPTION
**Pull request by JosephSalisbury**
Closes https://github.com/giantswarm/giantswarm/issues/13295

### CODE REVIEW

**Review by omegas27 — APPROVED** [review]

**Comment by omegas27** [comment]
Can I just know why?

**Comment by JosephSalisbury** [comment]
The default is 10, and that felt like a lot to me and mr @TheoBrigitte yesterday :D

We use this value a lot of other places - I basically just copied this from g8s-prometheus

**Comment by omegas27** [comment]
Sure, I was just wondering if it was causing issues. Should we maybe document it somewhere?

**Review by TheoBrigitte — APPROVED** [review]

**Review by mig4 — APPROVED** [review]
TIL about `revisionHistoryLimit` 😁 

I remember wondering at some point why are there so many old ReplicaSets of PMO hanging about 😅

**Pull request merged**
