### PR TITLE
Scrape some policy-reporter metrics from WCs

### PR DESCRIPTION
**Pull request by stone-z**
Towards https://github.com/giantswarm/giantswarm/issues/29351

Intends to scrape only metrics in the form `policy_result_summary{exported_namespace="...", "name="...", status="..."}` in order to measure PSS adoption impact and status.

## Checklist

I have:

- [x] Described why this change is being introduced
- [x] Separated out refactoring/reformatting in a dedicated PR
- [x] Updated changelog in `CHANGELOG.md`

### CODE REVIEW

**Comment by stone-z** [comment]
Hmm this doesn't seem to be getting any metrics from WCs when I try it on `gaia`. @giantswarm/team-atlas does this look right to you? Am I missing something obvious?

**Comment by QuentinBisson** [comment]
Is there a reason why you're not using a service monitor ?

**Comment by QuentinBisson** [comment]
To check why it's failing you Can check the service discovery page on prometheus :)

**Comment by stone-z** [comment]
> Is there a reason why you're not using a service monitor ?

Unfortunately, [yes](https://gigantic.slack.com/archives/C01176DKNP4/p1703017713527999)

> To check why it's failing you Can check the service discovery page on prometheus :)

I can see that they're being dropped but I can't work out why :bricks:

**Comment by QuentinBisson** [comment]
Can you deploy it tomorrow and let me know where so I Can check?

**Comment by stone-z** [comment]
This got ugly, replacing it with https://github.com/giantswarm/prometheus-meta-operator/pull/1570

**Pull request closed without merging**
