### PR TITLE
Align files

### PR DESCRIPTION
**Pull request by architectbot**
This PR is generated by https://github.com/giantswarm/github

### CODE REVIEW

**Comment by mig4** [comment]
Hmm, I think we still need this exception right?

**Comment by QuentinBisson** [comment]
Yes. One alertmanager is added, we can remove it though

**Comment by TheoBrigitte** [comment]
Yes we still need this exception, otherwise build complain about security issues. And I did not managed to upgrade our dependencies to a version where this is fixed without running into dependencies hell.

**Review by TheoBrigitte — APPROVED** [review]
I overwrotte the `.nancy-ignore` file here https://github.com/giantswarm/github/pull/229

**Pull request merged**
