### PR TITLE
security fixes

### PR DESCRIPTION
**Pull request by TheoBrigitte**
## Fixes:

- `go-kit/kit` : https://github.com/go-kit/kit/issues/1236
- `getsentry/sentry-go` : https://github.com/getsentry/sentry-go/issues/465

### CODE REVIEW

**Review by QuentinBisson — APPROVED** [review]

**Comment by TheoBrigitte** [comment]
Sorry I missed the draft button, this is not yet ready for review.

**Comment by TheoBrigitte** [comment]
Such a nice feeling  image

**Review by hervenicol — APPROVED** [review]
LGTM

**Comment by TheoBrigitte** [comment]
Upstream did merge some changes, I updated my PR, it looks ok and tests are green. They are just on pause this week. Supposedly merging next monday. Let's see.

**Pull request merged**
