### PR TITLE
Support absolute Grafana dashboard urls

### PR DESCRIPTION
**Pull request by QuentinBisson**
## Checklist

I have:

- [ ] Described why this change is being introduced
- [ ] Separated out refactoring/reformatting in a dedicated PR
- [ ] Updated changelog in `CHANGELOG.md`

### CODE REVIEW

**Comment by QuentinBisson** [comment]
So alertmanager template do not support hasPrefix https://prometheus.io/docs/alerting/latest/notifications/#functions

**Comment by QuentinBisson** [comment]
No errors in the logs:

```
ts=2023-09-25T11:21:32.877Z caller=coordinator.go:113 level=info component=configuration msg="Loading configuration file" file=/etc/alertmanager/config_out/alertmanager.env.yaml
ts=2023-09-25T11:21:32.880Z caller=coordinator.go:126 level=info component=configuration msg="Completed loading of configuration file" file=/etc/alertmanager/config_out/alertmanager.env.yaml
ts=2023-09-25T11:21:33.071Z caller=coordinator.go:113 level=info component=configuration msg="Loading configuration file" file=/etc/alertmanager/config_out/alertmanager.env.yaml
ts=2023-09-25T11:21:33.074Z caller=coordinator.go:126 level=info component=configuration msg="Completed loading of configuration file" file=/etc/alertmanager/config_out/alertmanager.env.yaml
```

**Review by hervenicol — APPROVED** [review]
Given the logs extracs, I guess this time it has been tested with a kill/restart of the alertmanager. Good with me then :+1:

**Comment by QuentinBisson** [comment]
Yes it was :)

**Pull request merged**
