### PR TITLE
switch to Aliyun Container Registry to Enterprise

### PR DESCRIPTION
**Pull request by kubasobon**

### CODE REVIEW

**Comment by hervenicol** [comment]
This means new images are pushed to new registry, but not available any more on old registry.
It means next release of this app has to be synchronized with a change of CN registry for it?

It seems quite touchy to me. Could we keep pushing to both registries for a while, to ease switch?

**Comment by kubasobon** [comment]
The old registry is still active and contains every tag pushed there. New tags/repositories should be pushed to new registry instead.
New registry has all the old repositories/tags imported though, so we're safe.

**Comment by hervenicol** [comment]
So, once this PR is merged, we can't upgrade until registry is switched.
I guess all is ready for the registry switch, and this is a very temporary situation?

**Review by hervenicol — APPROVED** [review]
Good luck with that migration :crossed_fingers: :four_leaf_clover:

**Comment by kubasobon** [comment]
Next release will just pull images from new registry. You're free to upgrade. Pulling does not require credentials.

**Pull request merged**
