### PR TITLE
increase memory request to 5Gi

### PR DESCRIPTION
**Pull request by TheoBrigitte**
Towards: https://github.com/giantswarm/giantswarm/issues/14076

### CODE REVIEW

**Review by JosephSalisbury — COMMENTED** [review]
do we have enough space for 5gi?

**Comment by TheoBrigitte** [comment]
Unsure, but that's what they do consume on average.

**Review by JosephSalisbury — APPROVED** [review]
let's roll and see, we can always update

**Comment by TheoBrigitte** [comment]
Seems like it will fit, let's roll.

image

**Pull request merged**
