### PR TITLE
Rename config names

### PR DESCRIPTION
**Pull request by QuentinBisson**
## Checklist

I have:

- [ ] Described why this change is being introduced
- [ ] Separated out refactoring/reformatting in a dedicated PR
- [ ] Updated changelog in `CHANGELOG.md`

### CODE REVIEW

**Review by TheoBrigitte — COMMENTED** [review]
Why do we need to pass all those new `Promtheus*` values around?

**Comment by QuentinBisson** [comment]
Sorry for not explaining. Basically, this is to namespace prometheus values because they conflict with alertmanager properties. They both have a Version, an Address and so on. Eventually, i'm thinking WE should use objets instead but I thought this would do for now

**Review by TheoBrigitte — APPROVED** [review]
Ok, thanks for the explanation.

Yeah it does feel silly to pass all those values around. Maybe we should just pass the entire flag struct instead. Let's refactor this later.

**Comment by mig4** [comment]
> Yeah it does feel silly to pass all those values around. Maybe we should just pass the entire flag struct instead. Let's refactor this later.

BIG +1 from me, let's make some re-usable structs, it's so annoying that when you add a flag you need to add it in dozen different places.

**Pull request merged**
