### PR TITLE
Clean up puma targets

### PR DESCRIPTION
**Pull request by QuentinBisson**
Puma's Prometheus is currently really slow. This PR should help reduce the load by removing not working targets 

## Checklist

I have:

- [x] Described why this change is being introduced
- [x] Separated out refactoring/reformatting in a dedicated PR
- [x] Updated changelog in `CHANGELOG.md`

### CODE REVIEW

**Comment by QuentinBisson** [comment]
This definitely sped up puma's prometheus. @giantswarm/team-atlas wdyt?

**Comment by QuentinBisson** [comment]
No issues to report on puma since I deployed this PR

**Review by TheoBrigitte — COMMENTED** [review]
I find it strange to have per installation config

**Comment by QuentinBisson** [comment]
I am not a big fan but we have this for dragon and dinosaur already and this is only temporary till all the kvm control plane are running the same hive version :( 
Theoretically, we could have this in the installation repo but having this from outside does not seem worth it right now. WDYT?

**Comment by TheoBrigitte** [comment]
> I am not a big fan but we have this for dragon and dinosaur already and this is only temporary till all the kvm control plane are running the same hive version :(
> Theoretically, we could have this in the installation repo but having this from outside does not seem worth it right now. WDYT?

Ok fine then, but let's make it a TODO and track somewhere when this should be removed, otherwise I'm afraid it will stay forever.

**Comment by QuentinBisson** [comment]
Clean up issue : https://github.com/giantswarm/giantswarm/issues/16921

**Comment by QuentinBisson** [comment]
I added the todo comments and linked the issue

**Comment by QuentinBisson** [comment]
Seems unneeded

**Pull request closed without merging**
