### PR TITLE
reconcile v1alpha4 cluster

### PR DESCRIPTION
**Pull request by TheoBrigitte**
Changed the logic to only reconcile v1alpha3 cluster, as the webhook conversion will do the conversion job for us.

The main change is that v1alpha3 is always used whether or not its the storage crd version. 

This solves all cases where AWS run v1alpha2 and v1alpha3 (as storage) and Azure runs v1alpha3 and v1alpha4 (as storage)

```
$ k --context giantswarm-ginger get crd clusters.cluster.x-k8s.io -oyaml|yq -y '.spec.versions[]|{name, storage}'
name: v1alpha2
storage: false
---
name: v1alpha3
storage: true
 k --context giantswarm-ghost get crd clusters.cluster.x-k8s.io -oyaml|yq -y '.spec.versions[]|{name, storage}'
name: v1alpha3
storage: false
---
name: v1alpha4
storage: true
```

### CODE REVIEW

**Comment by TheoBrigitte** [comment]
Tested on both aws/ginger and azure/ghost. Cluster can be created and deleted. :heavy_check_mark:

**Comment by QuentinBisson** [comment]
Can we not reconcile v1alph4 instead of v1alpha3 ?

**Comment by TheoBrigitte** [comment]
> Can we not reconcile v1alph4 instead of v1alpha3 ?

I don't think we should. How does this work on aws where only v1alpha3 and v1alpha2 are available?

**Comment by QuentinBisson** [comment]
Is v1alpha2 still available though ?

**Comment by TheoBrigitte** [comment]
Yes and v1alpha4 is not yet on aws installations AFAIK.

**Comment by QuentinBisson** [comment]
Good to know :D

**Review by QuentinBisson — APPROVED** [review]

**Pull request merged**
