### PR TITLE
configure new node inhibitions

### PR DESCRIPTION
**Pull request by QuentinBisson**
Towards https://github.com/giantswarm/prometheus-rules/pull/1207#discussion_r1660709836

This PR adds the new inhibition configuration that was added https://github.com/giantswarm/prometheus-rules/pull/1278

## Checklist

I have:

- [x] Described why this change is being introduced
- [x] Separated out refactoring/reformatting in a dedicated PR
- [x] Updated changelog in `CHANGELOG.md`

### CODE REVIEW

**Comment by marieroque** [comment]
I have a remark on that PR already merged.
Don't we need to add cluster_id in the expression ?
https://github.com/giantswarm/prometheus-rules/pull/1278/files#diff-a080240a1f817bf313dc69ebe0cbd903dc25aa88f03a59e92ce6718b097f9135R19

**Review by marieroque — APPROVED** [review]
LGTM 
Except my remark on the inhibition not taking in account the cluster_id

**Comment by QuentinBisson** [comment]
Why would we need that @marieroque ? We are missing an equal field with node, cluster_id on the inhibition though

**Comment by marieroque** [comment]
Right!

**Comment by QuentinBisson** [comment]
Thank you @marieroque

**Pull request merged**
