### PR TITLE
Update architect to 1.0.0

### PR DESCRIPTION
**Pull request by omegas27**

### CODE REVIEW

**Review by TheoBrigitte — APPROVED** [review]
LGTM

About the failing build, I've seen this error recently locally, but have no fix for it yet.

**Comment by omegas27** [comment]
I will ask in sig-releng, otherwise, we will have to remove the prometheus/prometheus dependency by copying the code

**Comment by omegas27** [comment]
The prometheus maintainers view on this pains me

**Comment by TheoBrigitte** [comment]
> I will ask in sig-releng, otherwise, we will have to remove the prometheus/prometheus dependency by copying the code

I'm not a fan of copying upstream code over.

**Comment by omegas27** [comment]
Me neither, but the prometheus maintainer keep saying this is internal code that we should not really use.

**Comment by omegas27** [comment]
They do not want to provide any kind of semver compability

**Comment by TheoBrigitte** [comment]
> Me neither, but the prometheus maintainer keep saying this is internal code that we should not really use.

I hate when they answer this.

**Pull request merged**
