### PR TITLE
evenly spread prometheus pods

### PR DESCRIPTION
**Pull request by TheoBrigitte**
Towards: https://github.com/giantswarm/giantswarm/issues/14076

This PR aims at better spreading prometheus pod on CPs.

The `TopologySpreadConstraints` should help evenly spread pods. see: https://pkg.go.dev/k8s.io/api/core/v1#TopologySpreadConstraint

### CODE REVIEW

**Review by omegas27 — APPROVED** [review]

**Comment by omegas27** [comment]
That looks interesting

**Comment by TheoBrigitte** [comment]
> That looks interesting

Yes indeed. I went this way because [`PodAffinityTerm`](https://pkg.go.dev/k8s.io/api/core/v1#PodAffinityTerm) only allow to match against pods in the same namespace.

```go
type PodAffinityTerm struct {
	// A label query over a set of resources, in this case pods.
	// +optional
	LabelSelector *metav1.LabelSelector `json:"labelSelector,omitempty" protobuf:"bytes,1,opt,name=labelSelector"`
	// namespaces specifies which namespaces the labelSelector applies to (matches against);
	// null or empty list means "this pod's namespace"
	// +optional
	Namespaces []string `json:"namespaces,omitempty" protobuf:"bytes,2,rep,name=namespaces"`
	// This pod should be co-located (affinity) or not co-located (anti-affinity) with the pods matching
	// the labelSelector in the specified namespaces, where co-located is defined as running on a node
	// whose value of the label with key topologyKey matches that of any node on which any of the
	// selected pods is running.
	// Empty topologyKey is not allowed.
	TopologyKey string `json:"topologyKey" protobuf:"bytes,3,opt,name=topologyKey"`
}
```

**Comment by TheoBrigitte** [comment]
Testes on `anteater`

```
$ k get po -lapp=prometheus -Aowide|grep -v Term|sort -k 8
NAMESPACE             NAME                          READY   STATUS    RESTARTS   AGE    IP                NODE                                         NOMINATED NODE   READINESS GATES
apie1-prometheus      prometheus-apie1-0            2/2     Running   1          45s    100.127.0.37      ip-172-19-5-200.eu-west-1.compute.internal   <none>           <none>
anteater-prometheus   prometheus-anteater-0         2/2     Running   1          56s    100.127.24.24     ip-172-19-5-200.eu-west-1.compute.internal   <none>           <none>
mh1m5-prometheus      prometheus-mh1m5-0            2/2     Running   1          37s    100.127.34.28     ip-172-19-5-200.eu-west-1.compute.internal   <none>           <none>
aud1t-prometheus      prometheus-aud1t-0            2/2     Running   1          48s    100.127.19.163    ip-172-19-5-200.eu-west-1.compute.internal   <none>           <none>
jbo5h-prometheus      prometheus-jbo5h-0            2/2     Running   1          41s    100.127.53.226    ip-172-19-5-200.eu-west-1.compute.internal   <none>           <none>
oaut1-prometheus      prometheus-oaut1-0            2/2     Running   1          56s    100.127.40.248    ip-172-19-5-200.eu-west-1.compute.internal   <none>           <none>
htq5q-prometheus      prometheus-htq5q-0            2/2     Running   1          52s    100.127.7.84      ip-172-19-5-202.eu-west-1.compute.internal   <none>           <none>
apie2-prometheus      prometheus-apie2-0            2/2     Running   1          47s    100.127.27.176    ip-172-19-5-202.eu-west-1.compute.internal   <none>           <none>
deu01-prometheus      prometheus-deu01-0            2/2     Running   1          43s    100.127.51.196    ip-172-19-5-202.eu-west-1.compute.internal   <none>           <none>
hype1-prometheus      prometheus-hype1-0            2/2     Running   1          50s    100.127.39.246    ip-172-19-5-202.eu-west-1.compute.internal   <none>           <none>
peu01-prometheus      prometheus-peu01-0            2/2     Running   1          54s    100.127.52.187    ip-172-19-5-202.eu-west-1.compute.internal   <none>           <none>
seu01-prometheus      prometheus-seu01-0            2/2     Running   1          39s    100.127.12.124    ip-172-19-5-202.eu-west-1.compute.internal   <none>           <none>
monitoring            prometheus-5cd5756967-czl8x   3/3     Running   0          101m   172.19.5.229      ip-172-19-5-229.eu-west-1.compute.internal   <none>           <none>
ceu01-prometheus      prometheus-ceu01-0            1/2     Running   1          35s    100.127.162.181   ip-172-19-5-229.eu-west-1.compute.internal   <none>           <none>
```

prometheus pods were evenly spread on woker nodes. There was 3 worker when doing this test.
* 6 prometheuses on `ip-172-19-5-200`
* 6 prometheuses on `ip-172-19-5-202`
* 1 prometheus on `ip-172-19-5-229`
* the big prometheus on `ip-172-19-5-229`

topology speading take the big prometheus into account because it has the same label <3


To get this working, we had to restart prometheuses and delete pvc
```
$ k delete prometheus -A --all
$ k delete pvc -lprometheus -A
```


Increasing memory request to 5Gi, based observations and this memory usage graph.


image

**Review by mig4 — APPROVED** [review]
🐙

**Comment by TheoBrigitte** [comment]
Hello @TheoBrigitte from 2021, you can merge this PR once you release prometheus-operator with the crd fix from https://github.com/giantswarm/giantswarm/issues/14326.

Love & kisses from @TheoBrigitte from 2020

**Comment by TheoBrigitte** [comment]
Merged master (52 new commits), and removed resources request/limits set by this PR as this was done somewhere else already.

**Pull request merged**
